### PR TITLE
fix: Fix and run ignored unit tests

### LINKED ISSUE #73: Fix failing tests
There are all kind of failing unit tests. Get these passing

### PR DESCRIPTION
**Pull request by BenjaminMichaelis**
Fixes #73

### CODE REVIEW

File: ListingManager/ListingManager.cs [hunk 1]
```diff
@@ -52,7 +52,7 @@ private static bool TryGetListing(string listingPath, out ListingInformation? li
         /// <param name="byFolder">Changes a listing's chapter based on the chapter number in the chapter's path</param>
         /// <param name="chapterOnly">Changes only the chapter of the listing, leaving the listing number unchanged. Use with <paramref name="byFolder"/></param>
         public static void UpdateChapterListingNumbers(string pathToChapter,
-            bool verbose = false, bool preview = false, bool byFolder = false, bool chapterOnly = false)
+            bool verbose = false, bool preview = false, bool byFolder = false, bool chapterOnly = false, bool singleDir = false)
```
Comment (Keboo) [inline ListingManager/ListingManager.cs:55]: Add XML docs for this new parameter?

**Review by Keboo — APPROVED** [review]

File: ListingManager/ListingManager.cs (hunk 1 above)
Comment (BenjaminMichaelis) [reply ListingManager/ListingManager.cs:56]: Done, thanks :)
